### ISSUE TITLE
Hangs on start with black window

### ISSUE THREAD

**Issue by Kookee2k2** [Hyphen-ated/RebirthItemTracker#124]
So basically for at least the past two versions I attempt to launch the tracker & all I get is the python window as a blank black window that windows reports that its not responding.

it doesnt even write anything to the tracker_log file
I have python 3.6 installed

**Comment by Hyphen-ated** [comment]
Can you try running from the command line and seeing if it prints any error text there?

It shouldn't matter what kind of python you have installed unless you're downloading the source code and running that. Is that what you're doing, or are you running an exe file from a release zip?

**Comment by Hyphen-ated** [comment]
Did a previous version of the tracker work for you?

**Comment by Kookee2k2** [comment]
- ran from command line, still gives me a blank dead window.
-- downloaded 1.2.4 and still gives me the same
- No i'm not running from source code, I jsut saw that python was used and I just so happened to have python installed (Although I've had this problem before I installed Python, tbh)
-- HAve uninstalled all versions of Python, and i still get the same result :/

**Comment by Kookee2k2** [comment]
oh, Windows actually gave me something this time. a couple of dump files in my appdata\local\temp
C:\Users\admin\AppData\Local\Temp\WER7651.tmp.xml


[d2.txt](https://github.com/Hyphen-ated/RebirthItemTracker/files/849021/d2.txt)


the 2nd file is some 25 megs
:/

**Comment by Hyphen-ated** [comment]
Can you post that 25mb file please?

**Comment by Gamerbiomek2** [comment]
program opens then closes on the new update 
the previous update works for me

**Comment by Hyphen-ated** [comment]
Sounds like a different issue. Did you check to see if there was anything in tracker_log.txt, gamerbiomek2? (please reply in a new thread)

**Comment by Kookee2k2** [comment]
I can't upload it here because of the 10mb limit.
luckly everyone and their mother has a google drive
so i just uploaded it to mine

https://drive.google.com/open?id=0Bw1rqxNpzpu0bmFVZ0hJNkNMY2c

**Comment by Hyphen-ated** [comment]
Thanks. This has a little bit of useful info for me.

I realized you didn't quite answer what I intended with a previous question: has **any** previous version of the tracker **ever** worked for you? You told me that you just tried 1.2.4 and that didn't work. If you've never had a working version, can you please try versions 0.1 and 0.8 and see if either of them gets past the same black-screen problem? 

https://github.com/Hyphen-ated/RebirthItemTracker/releases/download/0.1/RebirthItemTracker.0.1.zip

https://github.com/Hyphen-ated/RebirthItemTracker/releases/download/0.8/RebirthItemTracker-0.8.zip

**Comment by Gamerbiomek2** [comment]
here what the tracker log gets
[tracker_log.txt](https://github.com/Hyphen-ated/RebirthItemTracker/files/852076/tracker_log.txt)

**Comment by Gamerbiomek2** [comment]
here is what the tracker log gets

2017-03-17 21:58:50 Traceback (most recent call last):
  File "item_tracker.py", line 230, in main
  File "item_tracker.py", line 163, in run
  File "log_parser.py", line 47, in parse
  File "log_parser.py", line 256, in __load_log_file
TypeError: coercing to Unicode: need string or buffer, NoneType found

[tracker_log.txt](https://github.com/Hyphen-ated/RebirthItemTracker/files/852083/tracker_log.txt)

**Comment by Gamerbiomek2** [comment]
even the 2.0.2 just shows black and then closes
but i can still use 1.2.4

**Comment by Hyphen-ated** [comment]
Thanks. The tracker is crashing because it can't find the game's log.txt file. It's a bug that this causes a crash, but even once I fix that bug, it still won't display your items. Do you have a folder like C:\Users\<username>\Documents\My Games\Binding of Isaac Afterbirth+ ? And does it have a log.txt file in it?

**Comment by Gamerbiomek2** [comment]
I just have the folder on my desktop

**Comment by Hyphen-ated** [comment]
I'm not asking you about the item tracker folder. I'm asking you about a folder created by the game The Binding Of Isaac: Rebirth, inside your documents folder. Do you have that game installed, and have you run it?

**Comment by Gamerbiomek2** [comment]
there is a log.txt file in it
but I don't have rebirth+    just rebirth, afterbirth and antibirth

I have ran it

**Comment by Kookee2k2** [comment]
same black screen problems.

and YES it did work before. Weeks ago

**Comment by Hyphen-ated** [comment]
What version worked?

**Comment by Kookee2k2** [comment]
what ever version that was out when BOILeR started this year
[edit]
just incase you'd want to know what I installed since BOILeR started

![installed](https://cloud.githubusercontent.com/assets/26446967/24226607/c5a8e18e-0f3d-11e7-888a-d038b189dd25.png)

**Comment by Hyphen-ated** [comment]
1.2.4 (which you said doesn't work for you) was released on Jan 24, and it was the most up-to-date version until 2.0.0 was released on March 12. Boilr started on Feb 22, about in the middle of this period. So either you've made a mistake with the timeline, or something changed with your machine causing 1.2.4 to stop working for you.

Did you try the versions I asked you to try? Ideally, what I'd like to get from you is the identity of the newest version that still works for you. If you're willing to step through all the versions until you find the first one that experiences the problem, it's a lot more likely I'll be able to fix this. (if you are currently experiencing the problem even on version 0.1, then it's unlikely I'll be able to do anything for you)

**Comment by Kookee2k2** [comment]
on a side note, i went through my regedit with a couple of times, i deleted every mention of the tracker. still nothing. unless the executable is ran as something else. even tried pygame

also i did notice that there was a python27.dll (Python core, version 2.7.13150.yaddayadda) in the latest version, is there a way that I could get a version with python 3.6?

I'll look into on my end getting an old version of python installed and see how that works

[edit]
No, python27 didnt work maybe a conflict with the newer versions

**Comment by Hyphen-ated** [comment]
The tracker doesn't use the registry. Anything you're seeing in there that looks related is just stuff like Windows remembering the recent programs you've used, like it does for any generic exe you run. That doesn't mean it's impossible that your problem is caused by something in the registry, but it seems very unlikely.

Your installed version of python isn't relevant. You could have 10 different versions of python installed, or none at all, and none of that will be used by the tracker in any way at all, because it's been compiled into an exe and distributed with the dlls it uses. (unless you're running directly from the source code, but it sounds like you definitely aren't)

There's a python27 dll because the tracker is written in python 2. Replacing that with a python 3 dll will completely break everything, because the tracker is not written in python 3. I don't see a reason to port the tracker to python 3.

Have you tried previous versions of the tracker like I asked you to? I'm a little surprised that you're still putting effort into this, but haven't done that yet. Maybe I didn't explain well enough how to actually do it?

**Comment by Kookee2k2** [comment]
i've tried all of them

**Comment by Hyphen-ated** [comment]
and what was the result

**Comment by Gamerbiomek2** [comment]
nothing above 1.2.4 will work, they just keep closing when I open them D:

**Comment by Hyphen-ated** [comment]
you have a completely different problem gamerbiomek, that's why i asked you to reply by making a new thread a month ago
