### ISSUE TITLE
2.0.3 Opens then closes

### ISSUE THREAD

**Issue by Gamerbiomek2** [Hyphen-ated/RebirthItemTracker#130]
I open it and it just closes, not sure why it won't stay open

tracker log: 2017-04-29 22:40:59 Traceback (most recent call last):
  File "item_tracker.py", line 231, in main
  File "item_tracker.py", line 164, in run
  File "log_parser.py", line 48, in parse
  File "log_parser.py", line 253, in __load_log_file
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by zOrritOh** [comment]
Same with version 2.0.6 over here

2017-06-10 18:43:13 Traceback (most recent call last):
  File "item_tracker.py", line 231, in main
  File "item_tracker.py", line 164, in run
  File "log_parser.py", line 57, in parse
  File "log_parser.py", line 89, in __parse_line
  File "log_parser.py", line 142, in __parse_floor
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Hyphen-ated** [comment]
I forgot to reply to this ticket. This original issue I believe is fixed in 2.0.5

zorritoh, thanks for the report about this other bug. should be fixed in a new release soon

**Comment by Hyphen-ated** [comment]
this second bug should be fixed in 2.0.7
