### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#2]
IndexError: list index out of range
Traceback (most recent call last):
  File "item_tracker.py", line 452, in <module>
  File "item_tracker.py", line 372, in run

**Comment by Hyphen-ated** [comment]
it was crashing when trying to display info about the "selected item" but the selected index was larger than the size of the items array. I'm not sure how this can happen but I just put in a range check so it won't crash
