### ISSUE TITLE
crash on restart

### ISSUE THREAD

**Issue by hellfiremaga** [Hyphen-ated/RebirthItemTracker#74]
Hello

when I restart a game by keeping R pulled, the tracker crash and won't restart (the window only show for a second). The tracker log says : 

Traceback (most recent call last):
  File "item_tracker.py", line 581, in main
  File "item_tracker.py", line 498, in run
AttributeError: 'NoneType' object has no attribute 'group'

HAve I done something wrong?

**Comment by Hyphen-ated** [comment]
doesn't sound like you are doing anything wrong
can you please post your log.txt from Documents\My Games\Binding of Isaac Afterbirth\
and also your options.json from inside the tracker install dir

**Comment by hellfiremaga** [comment]
here is the log : 
timeBeginPeriod( 1 )
OpenGL version 4.5.13399 Compatibility Profile Context 15.201.1151.0
GLSL version 4.40
Framebuffer ID: 1
Renderbuffer ID: 1 size 1024x1024
New gamepad attached:
Description: XInput Controller 1
Vendor ID: 1118
Product ID: 654
Number of axes: 6
Number of buttons: 15
Binding of Isaac: Afterbirth v1.06.0077
Initialize ColorOffset Shader
Initialize Pixelation Shader
Initialize Bloom Shader
Initialize Color Correction Shader
Initialize HQ4X Shader
Initialize Shockwave Shader
Initialize OldTV Shader
Initialize Water Surface Shader

and here is the options
{
   "background_color": "#3C3C3C", 
   "bold_font": true, 
   "custom_message": "Seed: {seed} / Guppy: {guppy} / dmg: {dmg} / tears: {tears} / delay: {delay} / speed: {speed} / range: {range}", 
   "default_spacing": 64, 
   "framerate_limit": 30, 
   "height": 96, 
   "item_details_link": "http://platinumgod.co.uk/afterbirth?id=$ID", 
   "message_duration": 7, 
   "min_spacing": 24, 
   "show_blind_icon": true, 
   "show_custom_message": true, 
   "show_description": true, 
   "show_floors": true, 
   "show_font": "Arial", 
   "show_health_ups": true, 
   "show_rerolled_items": true, 
   "show_space_items": true, 
   "size_multiplier": 2.0, 
   "text_color": "#FFFFFF", 
   "width": 1366, 
   "word_wrap": false, 
   "x_position": 100, 
   "y_position": 100
}

**Comment by sillypears** [comment]
If that's all that is in the log file, it looks like the game isn't fully loading. The full log.txt file would need to be shown, so we can see why the tracker crashes when trying to parse the data in the log.txt as what you have is ignored by the tracker.

**Comment by Zamiell** [comment]
Close this for now, since the OP hasn't responded with more information and a newer version of the tracker is out now?
