### ISSUE TITLE
font crash

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#93]
puffinpunk was trying the 0.10-beta1 release and had a crash while changing fonts

Traceback (most recent call last):
  File "item_tracker.py", line 163, in main
  File "item_tracker.py", line 60, in run
  File "view_controls\view.py", line 56, in **init**
  File "view_controls\view.py", line 79, in start_pygame
  File "view_controls\view.py", line 441, in reset_options
  File "C:\Python27\lib\site-packages\pygame\sysfont.py", line 577, in SysFont
IOError: unable to read font filename

**Comment by Hyphen-ated** [comment]
they don't have a "C:\Python27". that's where my python is located though, and i built this release. (actually maybe that's just a stacktrace thing, it's showing where that file was when it was built)

 sounds like our font system is messed up.

**Comment by Hyphen-ated** [comment]
fixed this by wrapping the call to SysFont in a try/catch and falling back to arial
